// Code generated by 'yaegi extract github.com/MatusOllah/go-modloader-demo/mdk'. DO NOT EDIT.

package main

import (
	"github.com/MatusOllah/go-modloader-demo/mdk"
	"reflect"
)

func init() {
	Symbols["github.com/MatusOllah/go-modloader-demo/mdk/mdk"] = map[string]reflect.Value{
		// type definitions
		"Game":        reflect.ValueOf((*mdk.Game)(nil)),
		"ModMetadata": reflect.ValueOf((*mdk.ModMetadata)(nil)),
	}
}
